const $=x=>document.getElementById(x),DB="HameedLaundryV7",ST="orders";let orders=[];
function db(){return new Promise((a,b)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(ST,{keyPath:"id"});r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
async function all(){let d=await db();return new Promise((a,b)=>{let r=d.transaction(ST).objectStore(ST).getAll();r.onsuccess=()=>a(r.result||[]);r.onerror=()=>b(r.error)})}async function put(o){let d=await db();d.transaction(ST,"readwrite").objectStore(ST).put(o)}async function del(i){let d=await db();d.transaction(ST,"readwrite").objectStore(ST).delete(i)}
const today=()=>new Date().toISOString().slice(0,10),wd=d=>new Date(d+"T12:00:00").toLocaleDateString("ar",{weekday:"long"}),money=n=>Number(n||0).toFixed(2),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function groups(a){let m=new Map;a.forEach(o=>{let k=(o.phone||"").replace(/\s/g,"")||o.name;if(!m.has(k))m.set(k,{name:o.name,phone:o.phone,orders:[]});m.get(k).orders.push(o)});return[...m.values()]}
function week(){let b=today(),d=new Date();d.setDate(d.getDate()-6);return{a:d.toISOString().slice(0,10),b,list:orders.filter(o=>o.date>=d.toISOString().slice(0,10)&&o.date<=b)}}
function calc(){$("total").textContent=money((+$("weight").value||0)*(+$("price").value||0)+(+ $("extra").value||0))}
function report(){let w=week(),s=w.list.reduce((a,o)=>a+o.total,0),p=w.list.filter(o=>o.paid==="paid").reduce((a,o)=>a+o.total,0);$("rs").textContent=money(s);$("rp").textContent=money(p);$("ru").textContent=money(s-p);$("rc").textContent=groups(w.list).length;$("ro").textContent=w.list.length;$("ra").textContent=money(w.list.length?s/w.list.length:0);$("period").textContent=`الفترة: ${w.a} إلى ${w.b}`}
async function render(){orders=await all();let w=week(),q=$("search").value.toLowerCase(),t=orders.filter(o=>o.date===today());$("cc").textContent=groups(orders).length;$("oc").textContent=t.length;$("ws").textContent=money(w.list.reduce((a,o)=>a+o.total,0));$("wu").textContent=money(orders.filter(o=>o.paid==="unpaid").reduce((a,o)=>a+o.total,0));report();let gs=groups(orders).filter(c=>(c.name+" "+c.phone).toLowerCase().includes(q));$("customers").innerHTML=gs.map((c,i)=>{let sum=c.orders.reduce((a,o)=>a+o.total,0);return`<div class=customer id=c${i}><div class=head onclick="toggle('c${i}')"><div><b>👤 ${esc(c.name)}</b><small>📱 ${esc(c.phone)} — ${c.orders.length} معاملات</small></div><b>💰 ${money(sum)}</b></div><div class=body><div>كل معاملات الزبون: <b>${c.orders.length}</b></div>${c.orders.sort((a,b)=>b.id-a.id).map(o=>`<div class=order><b>${o.date} — ${esc(o.kind)}</b><br>⚖️ ${o.weight} كغم | 💰 ${money(o.total)} | 💳 ${o.paid==="paid"?"مدفوع":"غير مدفوع"}<br>📦 ${o.status==="washing"?"قيد الغسيل":o.status==="ready"?"جاهز للتسليم":"تم التسليم"}<div><button class=send onclick="send(${o.id})">💬 إرسال للزبون</button><button class=print onclick="prt(${o.id})">🖨️ طباعة</button><button onclick="edit(${o.id})">✏️ تعديل</button><button class=delete onclick="removeOrder(${o.id})">🗑️ حذف</button></div></div>`).join("")}</div></div>`}).join("");$("empty").style.display=gs.length?"none":"block"}
window.toggle=i=>$(i).classList.toggle("open");
window.removeOrder=async i=>{if(confirm("حذف المعاملة؟")){await del(i);await render()}};
window.edit=i=>{let o=orders.find(x=>x.id===i);["name","phone","kind","weight","price","extra","med","date","day","delivery","status","pay","paid","ref","notes"].forEach(k=>$(k).value=o[k]??"");$("eid").value=i;$("save").textContent="💾 حفظ التعديل";$("cancel").hidden=false;calc();scrollTo(0,0)};
$("form").onsubmit=async e=>{e.preventDefault();let w=+$("weight").value||0,p=+$("price").value||0,x=+$("extra").value||0;if(!$("name").value.trim()||!$("phone").value.trim()||w<=0)return;await put({id:+$("eid").value||Date.now(),name:$("name").value.trim(),phone:$("phone").value.trim(),kind:$("kind").value,weight:w,price:p,extra:x,total:w*p+x,medicine:$("med").value,date:$("date").value,day:$("day").value,delivery:$("delivery").value,status:$("status").value,payment:$("pay").value,paid:$("paid").value,paymentRef:$("ref").value,notes:$("notes").value});reset();render()};
function reset(){$("form").reset();$("eid").value="";$("date").value=today();$("day").value=wd(today());$("extra").value=0;$("save").textContent="💾 حفظ الطلب";$("cancel").hidden=true;calc()}$("cancel").onclick=reset;$("date").onchange=()=>$("day").value=wd($("date").value);["weight","price","extra"].forEach(i=>$(i).oninput=calc);$("search").oninput=render;
function excel(a,A,B){let g=groups(a),h=`<table><tr><th>الزبون</th><th>الهاتف</th><th>عدد الطلبات</th><th>الإجمالي</th><th>المدفوع</th><th>غير المدفوع</th></tr>`;g.forEach(c=>{let t=c.orders.reduce((s,o)=>s+o.total,0),p=c.orders.filter(o=>o.paid==="paid").reduce((s,o)=>s+o.total,0);h+=`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${c.orders.length}</td><td>${money(t)}</td><td>${money(p)}</td><td>${money(t-p)}</td></tr>`});h+=`</table><h3>تفاصيل الطلبات</h3><table><tr><th>التاريخ</th><th>الزبون</th><th>الهاتف</th><th>النوع</th><th>الوزن</th><th>الإجمالي</th><th>طريقة الدفع</th><th>حالة الدفع</th></tr>`;a.forEach(o=>h+=`<tr><td>${o.date}</td><td>${esc(o.name)}</td><td>${esc(o.phone)}</td><td>${esc(o.kind)}</td><td>${o.weight}</td><td>${money(o.total)}</td><td>${o.payment}</td><td>${o.paid==="paid"?"مدفوع":"غير مدفوع"}</td></tr>`);h+="</table>";let u=URL.createObjectURL(new Blob(["\ufeff<html><meta charset=UTF-8><style>td,th{border:1px solid #777;padding:7px}</style>"+h+"</html>"],{type:"application/vnd.ms-excel"})),a1=document.createElement("a");a1.href=u;a1.download=`مغسلة-حميد-${A}-الى-${B}.xls`;a1.click()}
$("excelReport").onclick=()=>{let w=week();excel(w.list,w.a,w.b)};$("excelCustom").onclick=()=>{let A=$("from").value,B=$("to").value;if(A&&B&&A<=B)excel(orders.filter(o=>o.date>=A&&o.date<=B),A,B)};
$("printReport").onclick=()=>{let w=week(),s=w.list.reduce((a,o)=>a+o.total,0),p=w.list.filter(o=>o.paid==="paid").reduce((a,o)=>a+o.total,0),u=window.open("","_blank");if(!u)return;u.document.write(`<html lang=ar dir=rtl><meta charset=utf-8><style>body{font-family:Tahoma;padding:25px}.box{display:inline-block;width:28%;padding:15px;margin:1%;background:#eee;text-align:center}.box b{display:block;font-size:24px;margin:8px}</style><h1>🧺 مغسلة حميد</h1><h2>التقرير الأسبوعي</h2><p>${w.a} إلى ${w.b}</p><div class=box>إجمالي المبيعات<b>${money(s)}</b></div><div class=box>المدفوع<b>${money(p)}</b></div><div class=box>غير المدفوع<b>${money(s-p)}</b></div><div class=box>عدد الزبائن<b>${groups(w.list).length}</b></div><div class=box>عدد الطلبات<b>${w.list.length}</b></div><div class=box>متوسط الطلب<b>${money(w.list.length?s/w.list.length:0)}</b></div><script>onload=()=>print()</script>`);u.document.close()};
window.send=i=>{let o=orders.find(x=>x.id===i),m=`أهلاً بك من مغسلة حميد 🌷\nالزبون: ${o.name}\nنوع الغسيل: ${o.kind}\nالوزن: ${o.weight} كغم\nالمبلغ: ${money(o.total)}\nالحالة: ${o.status==="ready"?"جاهز للتسليم":o.status==="delivered"?"تم التسليم":"قيد الغسيل"}`;let c=prompt("1 واتساب — 2 SMS","1");if(c==="1")location.href="https://wa.me/"+o.phone.replace(/\D/g,"")+"?text="+encodeURIComponent(m);else if(c==="2")location.href="sms:"+o.phone+"?body="+encodeURIComponent(m)};
window.prt=i=>{let o=orders.find(x=>x.id===i),w=window.open("","_blank");if(!w)return;w.document.write(`<html lang=ar dir=rtl><meta charset=utf-8><style>body{font-family:Tahoma;padding:25px}.x{padding:8px;border-bottom:1px solid #ccc}</style><h1>🧺 مغسلة حميد</h1><div class=x>الزبون: ${esc(o.name)}</div><div class=x>الهاتف: ${esc(o.phone)}</div><div class=x>النوع: ${esc(o.kind)}</div><div class=x>الوزن: ${o.weight} كغم</div><div class=x>التاريخ: ${o.date} — ${esc(o.day)}</div><div class=x>الإجمالي: <b>${money(o.total)}</b></div><script>onload=()=>print()</script>`);w.document.close()};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=7").catch(()=>{});(async()=>{await db();reset();await render()})();